### ISSUE TITLE
Next Release Plan (May 2021)

### ISSUE THREAD

**Issue by zobo** [xdebug/vscode-php-debug#575]
Following items are planned for the next release

- [x] Switch to Xdebug 3 default port 9003 #585
- [x] Auto local port and Xdebug parameters in command line #588
- [x] Built-in webserver start configuration #389
- [x] Launch configuration for Xdebug 2 #588
- [x] Fix for virtual source files in eval #574
- [x] Support for extended properties, helps with array key encoding issues #566
- [x] Change default Exception breakpoint settings #589
- [x] Extend logging with DBGp packets #586
