### ISSUE TITLE
Next Relelase Plan (September 2021)

### ISSUE THREAD

**Issue by zobo** [xdebug/vscode-php-debug#648]
Plan to work on PHP 8.1 and Xdebug 3.1 specific tasks.

- [x] hit-count breakpoint #69 #61 
- [x] enum facet #628 #655
- [x] readonly facet #627 #655
- [x] support for xdebug_notify #661 #647
- [ ] DBGp proxy #612
- [x] No folder debugging #638 #645

**Comment by zobo** [comment]
Moved DBGp proxy to next month.
