### ISSUE TITLE
Next Release Plan (February 2022)

### ISSUE THREAD

**Issue by zobo** [xdebug/vscode-php-debug#749]
- [ ] Xdebug cloud
- [ ] unix socket support #708
- [x] debug with stop on entry #724
- [x] log listening port #750
- [x] fix for extended root properties #752
